import type { StructureResolver } from 'sanity/structure';
import {
  LayoutDashboard,
  Megaphone,
  Calendar,
  Camera,
  BookOpen,
  GraduationCap,
  Users,
  Image,
  Target,
} from 'lucide-react';

export const structure: StructureResolver = (S) =>
  S.list()
    .id('root')
    .title('內容管理')
    .items([
      S.listItem()
        .id('dashboard')
        .title('首頁儀表板')
        .icon(LayoutDashboard)
        .child(
          S.component()
            .id('dashboard-view')
            .title('儀表板'),
        ),
      S.divider(),
      S.listItem()
        .id('announcements')
        .title('公告')
        .icon(Megaphone)
        .child(
          S.documentTypeList('announcement')
            .id('announcements-list')
            .title('公告'),
        ),
      S.listItem()
        .id('activities')
        .title('活動')
        .icon(Calendar)
        .child(
          S.documentTypeList('activity')
            .id('activities-list')
            .title('活動'),
        ),
      S.listItem()
        .id('memories')
        .title('回憶簿')
        .icon(Camera)
        .child(
          S.documentTypeList('memoryAlbum')
            .id('memories-list')
            .title('回憶簿'),
        ),
      S.listItem()
        .id('resources')
        .title('資源')
        .icon(BookOpen)
        .child(
          S.documentTypeList('resource')
            .id('resources-list')
            .title('資源'),
        ),
      S.divider(),
      S.listItem()
        .id('teachers')
        .title('顧問老師')
        .icon(GraduationCap)
        .child(
          S.documentTypeList('teacher')
            .id('teachers-list')
            .title('顧問老師'),
        ),
      S.listItem()
        .id('committee')
        .title('理事')
        .icon(Users)
        .child(
          S.documentTypeList('committee')
            .id('committee-list')
            .title('理事'),
        ),
      S.divider(),
      S.listItem()
        .id('gallery')
        .title('相冊')
        .icon(Image)
        .child(
          S.documentTypeList('gallery')
            .id('gallery-list')
            .title('相冊'),
        ),
      S.listItem()
        .id('homepage')
        .title('首頁內容')
        .icon(() => '🏠')
        .child(
          S.document()
            .id('homepage-doc')
            .schemaType('homepage')
            .documentId('homepage')
            .title('首頁內容'),
        ),
      S.listItem()
        .id('homepage-purpose')
        .title('回憶簿 — 目的')
        .icon(Target)
        .child(
          S.document()
            .id('homepage-purpose-doc')
            .schemaType('homepagePurpose')
            .documentId('homepagePurpose')
            .title('回憶簿目的'),
        ),
    ]);
