import type { StructureResolver } from 'sanity/structure';
import {
  LayoutDashboard,
  Megaphone,
  Calendar,
  Camera,
  BookOpen,
  GraduationCap,
  Users,
  Image,
  Target,
} from 'lucide-react';
import { Dashboard } from './components/Dashboard';

export const structure: StructureResolver = (S) =>
  S.list()
    .id('root')
    .title('内容管理')
    .items([
      S.listItem()
        .id('dashboard')
        .title('首页仪表板')
        .icon(LayoutDashboard)
        .child(
          S.component(Dashboard)
            .id('dashboard-view')
            .title('仪表板'),
        ),
      S.divider(),
      S.listItem()
        .id('announcements')
        .title('公告')
        .icon(Megaphone)
        .child(
          S.documentTypeList('announcement')
            .id('announcements-list')
            .title('公告'),
        ),
      S.listItem()
        .id('activities')
        .title('活动')
        .icon(Calendar)
        .child(
          S.documentTypeList('activity')
            .id('activities-list')
            .title('活动'),
        ),
      S.listItem()
        .id('memories')
        .title('回忆簿')
        .icon(Camera)
        .child(
          S.documentTypeList('memoryAlbum')
            .id('memories-list')
            .title('回忆簿'),
        ),
      S.listItem()
        .id('resources')
        .title('资源')
        .icon(BookOpen)
        .child(
          S.documentTypeList('resource')
            .id('resources-list')
            .title('资源'),
        ),
      S.divider(),
      S.listItem()
        .id('teachers')
        .title('顾问老师')
        .icon(GraduationCap)
        .child(
          S.documentTypeList('teacher')
            .id('teachers-list')
            .title('顾问老师'),
        ),
      S.listItem()
        .id('committee')
        .title('理事')
        .icon(Users)
        .child(
          S.documentTypeList('committee')
            .id('committee-list')
            .title('理事'),
        ),
      S.divider(),
      S.listItem()
        .id('gallery')
        .title('相册')
        .icon(Image)
        .child(
          S.documentTypeList('gallery')
            .id('gallery-list')
            .title('相册'),
        ),
      S.listItem()
        .id('homepage')
        .title('首页内容')
        .icon(() => '🏠')
        .child(
          S.document()
            .id('homepage-doc')
            .schemaType('homepage')
            .documentId('homepage')
            .title('首页内容'),
        ),
      S.listItem()
        .id('homepage-purpose')
        .title('首页 — 目的')
        .icon(Target)
        .child(
          S.document()
            .id('homepage-purpose-doc')
            .schemaType('homepagePurpose')
            .documentId('homepagePurpose')
            .title('首页目的'),
        ),
    ]);
